import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./AuthProvider";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-50 min-h-screen ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="w-full shadow flex items-center px-8 py-4 gap-6">
          <Link href="/" className="font-bold text-cyan-600 text-xl">CodeX</Link>
          <Link href="/" className="px-3 py-1 rounded hover:bg-cyan-500">User Profile</Link>
          <Link href="/events" className="px-3 py-1 rounded hover:bg-cyan-500">Manage Events</Link>
          <Link href="/user-dashboard" className="px-3 py-1 rounded hover:bg-cyan-500">User Dashboard</Link>
          <div className="flex-1" />
        </nav>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
